### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by hezhizhen**

### CODE REVIEW

**Comment by yihong0618** [comment]
@hezhizhen 
hi its a typo from another of my repo 
https://github.com/yihong0618/github-readme-stats

can you open a PR for that? thanks.

**Comment by yihong0618** [comment]
and just found all my language is a typo.....

**Comment by hezhizhen** [comment]
> and just found all my language is a typo.....

Correct. https://github.com/yihong0618/github-readme-stats/pull/12

**Comment by hezhizhen** [comment]
FYI, you can use https://github.com/crate-ci/typos CLI to quickly find some typos.

**Pull request merged**
